### ISSUE TITLE
Can you give an example of use with gulp-webserver

### ISSUE THREAD

**Issue by taufiqahmed** [turtlemay/gulp-mem#2]
gulp-webserver is compatible with connect middleware so I can use gulpMem.middleware as middleware with gulp-webserver. But I can't seem to set it up to work. The log says the file is wrote to the memory but after the servers starts it can't find the file in memory.

`gulpMem.serveBasePath = ./build`

```
gulp.src('./build ')
.pipe(webserver({middleware:gulpMem.middleware}));

Logs:
Writing file "/build/index.html" to memory
After server starts with gulp-webserver:
File "build/index.html" not found in memory

**Comment by turtlemay** [comment]
I neglected to handle unprefixed relative paths. Fixed and added example. f37f452380fff909720251cab57c7d48cb6df101 e331154a117649f5956f2b225aea6f658a70bb83

**Comment by turtlemay** [comment]
Published to npm.
